export const DEFAULT_FEE_PERCENTAGE = 5;
export const MOCK_EXCHANGE_RATE = 0.75; // 1 CNY = 0.75 BRL (Example)

export const DICTIONARY = {
  pt: {
    dashboard: "Painel",
    orders: "Pedidos",
    finance: "Financeiro",
    settings: "Configurações",
    pending: "Pendente",
    sent: "Enviado",
    finalized: "Finalizado",
    dispute: "Disputa",
    uploadPhotos: "Anexar Fotos",
    trackingCode: "Código de Rastreio",
    save: "Salvar",
    withdraw: "Solicitar Saque",
    available: "Disponível",
    totalRelease: "Total a Liberar",
    receivedToday: "Recebido Hoje",
    pendingShipment: "Pendente de Envio",
    myId: "Meu ID",
    copy: "Copiar",
    copied: "Copiado!",
    waitingApproval: "Aguardando Aprovação",
    yourAccountPending: "Sua conta está sob análise do administrador.",
    logout: "Sair",
    clients: "Clientes",
    suppliers: "Fornecedores",
    approve: "Aprovar",
    reject: "Recusar",
    block: "Bloquear",
    adminPanel: "Painel Admin",
    clientPanel: "Área do Cliente",
    supplierPanel: "Área do Fornecedor",
    welcome: "Bem-vindo",
    calculator: "Calculadora de Taxas",
    tutorial: "Como funciona?",
    tutorialText: "Insira o valor em Yuan. O sistema calcula o total em Reais incluindo a taxa de serviço.",
    supplierIdLabel: "ID do Fornecedor",
    enterSupplierId: "Insira o ID de 6 dígitos",
    createOrder: "Simular Novo Pedido",
    confirm: "Confirmar",
    cancel: "Cancelar",
    reason: "Motivo",
    submitDispute: "Enviar Disputa",
    noOrders: "Nenhum pedido encontrado.",
    receivedWeek: "Recebido esta Semana",
    history: "Histórico",
    requestSuccess: "Solicitação enviada com sucesso!",
    uploadProof: "Anexar Comprovante",
    viewProof: "Ver Comprovante",
  },
  zh: {
    dashboard: "仪表板 (Dashboard)",
    orders: "订单 (Orders)",
    finance: "财务 (Finance)",
    settings: "设置 (Settings)",
    pending: "待处理 (Pending)",
    sent: "已发货 (Sent)",
    finalized: "已完成 (Finalized)",
    dispute: "争议 (Dispute)",
    uploadPhotos: "上传照片 (Upload Photos)",
    trackingCode: "追踪号码 (Tracking Code)",
    save: "保存 (Save)",
    withdraw: "申请提现 (Request Withdraw)",
    available: "可用余额 (Available)",
    totalRelease: "待释放总额 (Total to Release)",
    receivedToday: "今日收到 (Received Today)",
    pendingShipment: "待发货 (Pending Shipment)",
    myId: "我的ID (My ID)",
    copy: "复制 (Copy)",
    copied: "已复制 (Copied!)",
    waitingApproval: "等待批准 (Waiting Approval)",
    yourAccountPending: "您的帐户正在等待管理员审核。(Account under review)",
    logout: "登出 (Logout)",
    clients: "客户 (Clients)",
    suppliers: "供应商 (Suppliers)",
    approve: "批准 (Approve)",
    reject: "拒绝 (Reject)",
    block: "封锁 (Block)",
    adminPanel: "管理面板 (Admin Panel)",
    clientPanel: "客户区 (Client Area)",
    supplierPanel: "供应商区 (Supplier Area)",
    welcome: "欢迎 (Welcome)",
    calculator: "汇率计算器 (Calculator)",
    tutorial: "如何运作? (How it works?)",
    tutorialText: "输入人民币金额。系统计算包含服务费的雷亚尔总额。(Input Yuan, get BRL + fee)",
    supplierIdLabel: "供应商ID (Supplier ID)",
    enterSupplierId: "输入6位ID (Enter 6-digit ID)",
    createOrder: "创建订单 (Create Order)",
    confirm: "确认 (Confirm)",
    cancel: "取消 (Cancel)",
    reason: "原因 (Reason)",
    submitDispute: "提交争议 (Submit Dispute)",
    noOrders: "未找到订单 (No orders found)",
    receivedWeek: "本周收到 (Received this week)",
    history: "历史记录 (History)",
    requestSuccess: "请求发送成功! (Success!)",
    uploadProof: "上传凭证 (Upload Proof)",
    viewProof: "查看凭证 (View Proof)",
  }
};